#!/bin/sh

CDATE=$(date "+%Y-%m-%d")
RELEASE="zap-kernel-$CDATE"
LAST_RELEASE=$(git tag | grep "zap-kernel" | tail -1)

printf "Appending ZAP changes to changes.txt...\n"
if [ -n "$LAST_RELEASE" ]; then
  printf "## Changelog:\n" > changes.txt
  git log --oneline "$LAST_RELEASE"^..HEAD >> changes.txt
else
  printf "\nInitial release. Using zdiff.sh..."
  printf "## ZAP Changes:\n" > changes.txt
  sh zap/zdiff.sh
  cat zap/changes.log >> changes.txt
fi

cat changes.txt
printf "\nPress ENTER to upload %s to GitHub." "$RELEASE" && \
  head -n 1 > /dev/null

printf "\nGenerating and pushing a signed tag..."
git tag -s -a "$RELEASE" -m "Tag for release $RELEASE."
git push origin "$RELEASE"

printf "\nCreating a release for GitHub and uploading files..."
gh release create -F changes.txt -t "$RELEASE" "$RELEASE"

for target in out/*; do
  if [ ! -d "$target" ]; then
    break
  fi

  printf "\nSigning %s zip file..." "$target"
  gpg --detach-sign --armor --output \
    "out/$target/zap-kernel_$target-$CDATE.zip.asc" \
    "out/$target/zap-kernel_$target-$CDATE.zip"

  printf "\nUploading file and signature for %s..." "$target"
  gh release upload "$RELEASE" \
    "out/$target/zap-kernel_$target-$CDATE.zip.asc" \
    "out/$target/zap-kernel_$target-$CDATE.zip"
done

printf "\nFinished. Cleaning up extra file(s)...\n"
rm -f zap/changes.log changes.txt
